name: rob stephenson
favicon: null
layout_spectrum: 0.88141
typography_spectrum: 0.49038
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020000'
    - '#33220c'
    - '#ff942d'
    - '#84552a'
    - '#d66c29'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose: []
